name: .NET 6 Build

on:
  push:
    branches: [trunk ]
  pull_request:
    branches: [trunk ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ğŸ› 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setting directory
      uses: ./source
    - name: Restore dependencies ğŸ”
      run: dotnet restore
    - name: Build ğŸš§
      run: dotnet build --no-restore
    - name: Test ğŸ§ª
      run: dotnet test --no-build --verbosity normal
